# -*- coding: utf-8 -*-
"""Copy of DP:autoFAQ.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1OL-h0sB7xf3po7v9FYqSKcfIad4cUEC5
"""

pip install -q deeppavlov

# Commented out IPython magic to ensure Python compatibility.
# %load https://raw.githubusercontent.com/deepmipt/DeepPavlov/master/deeppavlov/configs/faq/tfidf_logreg_en_faq.json

!python -m deeppavlov install tfidf_logreg_en_faq

!python -m deeppavlov interact tfidf_logreg_en_faq -d

"""Alternatively, you can **build_model** from the Python code as on the example below. In addition, please make sure that you can navigate the configuration files by using Autocomplete (Tab key) with **configs** module."""

pip install deeppavlov

from deeppavlov import configs
from deeppavlov.core.common.file import read_json
from deeppavlov.core.commands.infer import build_model

faq = build_model(configs.squad.squad_ru_bert, download = True)
a = faq(["I need help"])
a

pip install git+https://github.com/deepmipt/bert.git@feat/multi_gpu

from deeppavlov import build_model, configs

model = build_model(configs.squad.squad_ru_bert, download=True)
model(['Борис видит как люди видят красоту ходят направо  налево прямо  назад. '], ['Что видит Борис?'])
